# <u>Python Analytics Project (CIS442)</u>
## By - Bingqiong Sun, Shiwei Ran(Victoria), Chuanji Chen, Tushar Mathur


# <u>1. Setting</u>

###  We are using a dataset obtained from <a href=https://data.gov.uk/>www.data.gov.uk</a>
### This dataset includes data on road accidents that occurred in Leeds, UK over a span of 6 years from 2010 to 2015. This is the link to our dataset - <a href https://data.gov.uk/dataset/road-traffic-accidents> Leeds Traffic accident data </a>

### We believe that if we can build a predictive model that can successfully predict an accident, it would be beneficial to everyone as road accidents occur all across the world.

# <u>2. Data</u>

###  Information on accidents across Leeds. Data includes location, number of people and vehicles involved, road surface, weather conditions and severity of any casualties.

### The initial data that is on the wesbite, is in separate csv files. Each file has data for a specific calendar year. we combined all the data into a single csv file. Our file containes 13068 observations with 15 variables.

### We cleaned the data by removing certain variables that we think were not necessary for our model. After the data cleaning process our data has 9 variables which are - 

#### 1. Number of vehicles
#### 2. TIme of the accident
#### 3. Road class
#### 4. Road Surface
#### 5. Lighting conditions
#### 6. Weather conditions
#### 7. Sex of casualty
#### 8. Age of casualty
#### 9.Casualty severity


### The primary challenege we faced while cleaning the data was to identify the variables that would add value to our model, and remove the variables that would be redundant for our model. Secondly, we had to change the values of some variables to catergoial values. For example, we modified the time of the day to four catergories, 'morning', 'afternoon', 'evening' and 'night'.



### Upon graphically viewing the data from this dataset, we realised that the maximum number of occurred when the road conditions were dry, or when the weather conditions were fine without high winds, or when there were street lights on the road. This proves that desite having good driving conditions, the number of accidents are high. Hence it is extremley crucial to build a model that can predict an accident. 

In [1]:
from IPython.display import Image # displaying images files in jupyter
from IPython.display import IFrame 
IFrame('light.pdf', width=900, height=800) 

In [2]:
IFrame('weather.pdf', width=900, height=800) 

In [3]:
IFrame('road.pdf', width=900, height=800) 

## Part 1: Getting the data ready

## Part 2: Analyzing the data

In [4]:
# Support vector machine


In [16]:
import numpy as np
import pandas as pd
ab = pd.read_csv('data_v5.csv',encoding='windows-1252')
ab.head()

Number_of_Vehicles    Road_Class Road_Surface  \
0                   2  Unclassified   Wet / Damp   
1                   2  Unclassified   Wet / Damp   
2                   1  Unclassified   Frost/ Ice   
3                   2  Unclassified   Wet / Damp   
4                   2          A(M)   Wet / Damp   

                       Lighting_Conditions          Weather_Conditions  \
0  Darkness: street lights present and lit  Snowing without high winds   
1  Darkness: street lights present and lit     Fine without high winds   
2  Darkness: street lights present and lit     Fine without high winds   
3  Darkness: street lights present and lit     Fine without high winds   
4  Darkness: street lights present and lit     Fine without high winds   

  Sex_of_Casualty  Age_of_Casualty                         Type_of_Vehicle  \
0          Female               62                                     Car   
1            Male               36  Goods vehicle 3.5 tonnes mgw and under   
2          Female               34  Goods vehicle 3.5 tonnes mgw and under   
3            Male               27                                     Car   
4            Male               18                                     Car   

  Type_of_Vehicle2 New_time          ...           Sex_of_Casualty_Male  \
0              car      day          ...                              0   
1    Goods vehicle    night          ...                              1   
2    Goods vehicle    night          ...                              0   
3              car    night          ...                              1   
4              car    night          ...                              1   

   Type_of_Vehicle_Agricultural vehicle  Type_of_Vehicle_Goods vehicle  \
0                                     0                              0   
1                                     0                              1   
2                                     0                              1   
3                                     0                              0   
4                                     0                              0   

   Type_of_Vehicle_Mobility Scooter  Type_of_Vehicle_Motorcycle  \
0                                 0                           0   
1                                 0                           0   
2                                 0                           0   
3                                 0                           0   
4                                 0                           0   

   Type_of_Vehicle_Pedal cycle  Type_of_Vehicle_Ridden horse  \
0                            0                             0   
1                            0                             0   
2                            0                             0   
3                            0                             0   
4                            0                             0   

   Type_of_Vehicle_bus  Type_of_Vehicle_car  Type_of_Vehicle_rail  
0                    0                    1                     0  
1                    0                    0                     0  
2                    0                    0                     0  
3                    0                    1                     0  
4                    0                    1                     0  

[5 rows x 49 columns]

In [17]:
ab_time = pd.get_dummies(ab['New_time'],prefix='time')
ab_time.head()

ab = pd.concat([ab, ab_time], axis=1)
ab.head()

Number_of_Vehicles    Road_Class Road_Surface  \
0                   2  Unclassified   Wet / Damp   
1                   2  Unclassified   Wet / Damp   
2                   1  Unclassified   Frost/ Ice   
3                   2  Unclassified   Wet / Damp   
4                   2          A(M)   Wet / Damp   

                       Lighting_Conditions          Weather_Conditions  \
0  Darkness: street lights present and lit  Snowing without high winds   
1  Darkness: street lights present and lit     Fine without high winds   
2  Darkness: street lights present and lit     Fine without high winds   
3  Darkness: street lights present and lit     Fine without high winds   
4  Darkness: street lights present and lit     Fine without high winds   

  Sex_of_Casualty  Age_of_Casualty                         Type_of_Vehicle  \
0          Female               62                                     Car   
1            Male               36  Goods vehicle 3.5 tonnes mgw and under   
2          Female               34  Goods vehicle 3.5 tonnes mgw and under   
3            Male               27                                     Car   
4            Male               18                                     Car   

  Type_of_Vehicle2 New_time     ...      Type_of_Vehicle_Goods vehicle  \
0              car      day     ...                                  0   
1    Goods vehicle    night     ...                                  1   
2    Goods vehicle    night     ...                                  1   
3              car    night     ...                                  0   
4              car    night     ...                                  0   

   Type_of_Vehicle_Mobility Scooter  Type_of_Vehicle_Motorcycle  \
0                                 0                           0   
1                                 0                           0   
2                                 0                           0   
3                                 0                           0   
4                                 0                           0   

   Type_of_Vehicle_Pedal cycle  Type_of_Vehicle_Ridden horse  \
0                            0                             0   
1                            0                             0   
2                            0                             0   
3                            0                             0   
4                            0                             0   

   Type_of_Vehicle_bus  Type_of_Vehicle_car  Type_of_Vehicle_rail  time_day  \
0                    0                    1                     0       1.0   
1                    0                    0                     0       0.0   
2                    0                    0                     0       0.0   
3                    0                    1                     0       0.0   
4                    0                    1                     0       0.0   

   time_night  
0         0.0  
1         1.0  
2         1.0  
3         1.0  
4         1.0  

[5 rows x 51 columns]

In [18]:
dummydata = ab.ix[:,10:]
dummydata.head()




Severity2  Road_Class_A  Road_Class_A(M)  Road_Class_B  Road_Class_C  \
0          3             0                0             0             0   
1          3             0                0             0             0   
2          3             0                0             0             0   
3          3             0                0             0             0   
4          3             0                1             0             0   

   Road_Class_Motorway  Road_Class_Unclassified  Road_Class_A.1  \
0                    0                        1               0   
1                    0                        1               0   
2                    0                        1               0   
3                    0                        1               0   
4                    0                        0               0   

   Road_Class_A(M).1  Road_Class_B.1     ...      \
0                  0               0     ...       
1                  0               0     ...       
2                  0               0     ...       
3                  0               0     ...       
4                  1               0     ...       

   Type_of_Vehicle_Goods vehicle  Type_of_Vehicle_Mobility Scooter  \
0                              0                                 0   
1                              1                                 0   
2                              1                                 0   
3                              0                                 0   
4                              0                                 0   

   Type_of_Vehicle_Motorcycle  Type_of_Vehicle_Pedal cycle  \
0                           0                            0   
1                           0                            0   
2                           0                            0   
3                           0                            0   
4                           0                            0   

   Type_of_Vehicle_Ridden horse  Type_of_Vehicle_bus  Type_of_Vehicle_car  \
0                             0                    0                    1   
1                             0                    0                    0   
2                             0                    0                    0   
3                             0                    0                    1   
4                             0                    0                    1   

   Type_of_Vehicle_rail  time_day  time_night  
0                     0       1.0         0.0  
1                     0       0.0         1.0  
2                     0       0.0         1.0  
3                     0       0.0         1.0  
4                     0       0.0         1.0  

[5 rows x 41 columns]

In [23]:
X_labels = [c for c in dummydata.columns if c not in ['Severity2']]
X = dummydata.ix[:,X_labels]
Y = dummydata['Severity2']

In [25]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [46]:
lm.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [43]:
estimated_coefficients = pd.DataFrame(columns=['features','estimated coefficients'])
estimated_coefficients['features']=X.columns
estimated_coefficients['estimated coefficients']=lm.coef_
estimated_coefficients

features  estimated coefficients
0                                        Road_Class_A            2.689851e+11
1                                     Road_Class_A(M)           -4.193554e+10
2                                        Road_Class_B           -1.709998e+10
3                                        Road_Class_C           -2.461081e+10
4                                 Road_Class_Motorway           -2.779303e+10
5                             Road_Class_Unclassified           -2.627947e+10
6                                      Road_Class_A.1           -3.007010e+11
7                                   Road_Class_A(M).1            1.021967e+10
8                                      Road_Class_B.1           -1.461589e+10
9                                      Road_Class_C.1           -7.105065e+09
10                              Road_Class_Motorway.1           -3.922840e+09
11                          Road_Class_Unclassified.1           -5.436400e+09
12                              Lighting_Conditions_5            2.130242e+12
13   Lighting_Conditions_Darkness: no street lighting            2.130242e+12
14  Lighting_Conditions_Darkness: street lighting ...            2.130242e+12
15  Lighting_Conditions_Darkness: street lights pr...            2.130242e+12
16  Lighting_Conditions_Darkness: street lights pr...            2.130242e+12
17  Lighting_Conditions_Daylight: street lights pr...            2.130242e+12
18            Weather_Conditions_Fine with high winds            5.544962e+10
19         Weather_Conditions_Fine without high winds            5.544962e+10
20         Weather_Conditions_Fog or mist – if hazard            5.544962e+10
21                           Weather_Conditions_Other            5.544962e+10
22         Weather_Conditions_Raining with high winds            5.544962e+10
23      Weather_Conditions_Raining without high winds            5.544962e+10
24         Weather_Conditions_Snowing with high winds            5.544962e+10
25      Weather_Conditions_Snowing without high winds            5.544962e+10
26                         Weather_Conditions_Unknown            5.544962e+10
27                             Sex_of_Casualty_Female           -3.158867e+10
28                               Sex_of_Casualty_Male           -3.158867e+10
29               Type_of_Vehicle_Agricultural vehicle            2.744027e+10
30                      Type_of_Vehicle_Goods vehicle            2.744027e+10
31                   Type_of_Vehicle_Mobility Scooter            2.744027e+10
32                         Type_of_Vehicle_Motorcycle            2.744027e+10
33                        Type_of_Vehicle_Pedal cycle            2.744027e+10
34                       Type_of_Vehicle_Ridden horse            2.744027e+10
35                                Type_of_Vehicle_bus            2.744027e+10
36                                Type_of_Vehicle_car            2.744027e+10
37                               Type_of_Vehicle_rail            2.744027e+10
38                                           time_day            1.742554e-02
39                                         time_night           -1.742554e-02

In [48]:
#scores
lm.score(X,Y)

0.044442624972681255

In [50]:
#tree
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [51]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,Y)

In [52]:
clf.score(X, Y)

0.8849993681283963

In [55]:
#svc linear and poly
from sklearn import svm # read more at: scikit-learn.org
from sklearn.model_selection import cross_val_score
from sklearn.svm import LinearSVC

clf1 = svm.SVC(kernel='linear')
clf1.fit(X, Y)
scores1=cross_val_score(clf, X, Y, cv=5)
scores1

array([ 0.87523689,  0.87523689,  0.85687204,  0.87772512,  0.86188369])

In [58]:
scores1.mean()

0.86939092637646598

In [56]:
clf2 = svm.SVC(kernel='poly',degree=2)
clf2.fit(X, Y)
scores2=cross_val_score(clf, X, Y, cv=5)
scores2

array([ 0.87492104,  0.87555275,  0.85655608,  0.87804107,  0.86156764])

In [59]:
scores2.mean()

0.86932771525130792

In [57]:
clf3 = svm.SVC(kernel='poly',degree=3)
clf3.fit(X, Y)
scores3=cross_val_score(clf, X, Y, cv=5)
scores3

array([ 0.87523689,  0.87523689,  0.85687204,  0.87804107,  0.86156764])

In [70]:
scores3.mean()

0.86939090640454653

In [77]:
accuracy = [lm.score(X,Y),clf.score(X, Y),scores1.mean(),scores2.mean(),scores3.mean()]
accuracy

[0.044442624972681255,
 0.8849993681283963,
 0.86939092637646598,
 0.86932771525130792,
 0.86939090640454653]

In [5]:
import numpy as np
import pandas as pd
import scipy 
import scipy.stats as stats
import matplotlib.pyplot as plt
from IPython.display import Image
from scipy import misc
from scipy.spatial import distance
from scipy.cluster import hierarchy
from sklearn import cluster
from sklearn import svm
from sklearn import datasets
from sklearn import mixture
from sklearn.model_selection import cross_val_score
from mpl_toolkits.mplot3d import axes3d
from ipywidgets import interact
from matplotlib import cm
from matplotlib.colors import LogNorm
np.set_printoptions(precision=1)
%matplotlib inline

kmeans = cluster.KMeans(n_clusters=20).fit(dummydata)
kmeans.labels_

array([10,  2, 13, ..., 17, 10,  7], dtype=int32)

In [15]:
#dummydata['class']=kmeans.labels_
kmeans.cluster_centers_
centroids = pd.DataFrame(data=kmeans.cluster_centers_)
centroids['class']=range(centroids.shape[0])
centroids

0             1             2             3             4  \
0   2.951807 -2.775558e-15 -3.434752e-16 -2.012279e-16 -1.149254e-17   
1   2.815603  9.989868e-01 -1.179612e-16 -9.853229e-16  1.013171e-03   
2   2.856129  3.108624e-15  2.359224e-16 -1.561251e-15  1.935484e-03   
3   2.921767  1.000000e+00  1.734723e-16 -1.582068e-15  1.192622e-17   
4   1.929487 -1.165734e-15  2.775558e-17 -2.081668e-16  3.205128e-03   
5   2.910162  1.000000e+00  1.665335e-16 -1.415534e-15  3.686287e-18   
6   2.924686 -3.164136e-15 -1.526557e-16 -9.298118e-16 -2.038300e-17   
7   2.786015  1.000000e+00  5.898060e-17 -1.249001e-15 -4.553649e-18   
8   2.851852 -2.442491e-15 -2.255141e-16  1.000000e+00 -2.818926e-18   
9   2.922118 -1.221245e-15  2.775558e-17 -1.734723e-16  4.336809e-18   
10  3.000000  1.998401e-15  2.463307e-16 -1.540434e-15  1.319261e-03   
11  2.828619 -2.609024e-15 -2.879641e-16  4.857226e-17  3.327787e-03   
12  1.947368  7.771561e-16  2.775558e-17 -1.734723e-16  3.686287e-18   
13  2.894137 -2.609024e-15 -3.018419e-16 -6.938894e-18 -8.456777e-18   
14  2.908815 -1.332268e-15  1.000000e+00 -1.457168e-16  4.553649e-18   
15  2.902887 -1.720846e-15  3.122502e-17  1.000000e+00  4.553649e-18   
16  3.000000  7.938095e-15 -4.510281e-17 -1.658396e-15  2.329645e-03   
17  2.879870  1.000000e+00 -3.018419e-16 -1.387779e-17 -8.673617e-18   
18  2.951872  1.000000e+00  2.775558e-17 -1.665335e-16  3.469447e-18   
19  2.911628  2.220446e-16  2.775558e-17 -2.498002e-16  1.860465e-02   

               5             6             7             8             9  \
0   2.636780e-16  1.000000e+00 -2.775558e-15 -3.434752e-16 -2.012279e-16   
1   2.775558e-16 -3.608225e-15  9.989868e-01 -1.179612e-16 -9.853229e-16   
2   2.844947e-16  9.980645e-01  3.108624e-15  2.359224e-16 -1.561251e-15   
3   2.844947e-16 -3.830269e-15  1.000000e+00  1.734723e-16 -1.582068e-15   
4   2.289835e-16  9.967949e-01 -1.165734e-15  2.775558e-17 -2.081668e-16   
5   2.844947e-16 -3.719247e-15  1.000000e+00  1.665335e-16 -1.415534e-15   
6   1.000000e+00 -3.552714e-15 -3.164136e-15 -1.526557e-16 -9.298118e-16   
7   2.844947e-16 -3.663736e-15  1.000000e+00  5.898060e-17 -1.249001e-15   
8   2.498002e-16 -2.942091e-15 -2.442491e-15 -2.255141e-16  1.000000e+00   
9   2.289835e-16  1.000000e+00 -1.221245e-15  2.775558e-17 -1.734723e-16   
10  2.844947e-16  9.986807e-01  1.998401e-15  2.463307e-16 -1.540434e-15   
11  2.567391e-16  9.966722e-01 -2.609024e-15 -2.879641e-16  4.857226e-17   
12  1.734723e-16  1.000000e+00  7.771561e-16  2.775558e-17 -1.734723e-16   
13  2.567391e-16  1.000000e+00 -2.609024e-15 -3.018419e-16 -6.938894e-18   
14  2.289835e-16 -2.164935e-15 -1.332268e-15  1.000000e+00 -1.457168e-16   
15  2.428613e-16 -2.442491e-15 -1.720846e-15  3.122502e-17  1.000000e+00   
16  2.914335e-16  9.976704e-01  7.938095e-15 -4.510281e-17 -1.658396e-15   
17  2.567391e-16 -3.108624e-15  1.000000e+00 -3.018419e-16 -1.387779e-17   
18  1.734723e-16 -5.551115e-16  1.000000e+00  2.775558e-17 -1.665335e-16   
19  1.873501e-16  9.813953e-01  2.220446e-16  2.775558e-17 -2.498002e-16   

    ...              32            33            34            35  \
0   ...    3.012048e-03  5.572289e-02  1.039157e-01  3.012048e-03   
1   ...   -1.398621e-17  8.611955e-02  8.206687e-02 -2.818926e-18   
2   ...   -1.843144e-17  7.935484e-02  7.096774e-02 -8.185726e-18   
3   ...    6.309148e-04  2.649842e-02  6.561514e-02  6.309148e-04   
4   ...    6.410256e-03  3.942308e-01  3.205128e-03 -9.757820e-19   
5   ...   -1.734723e-17  1.609823e-15 -1.332268e-15 -6.830474e-18   
6   ...   -1.355253e-17  2.510460e-02 -3.747003e-16 -2.331035e-18   
7   ...   -1.604619e-17  2.965459e-01  5.012637e-01 -5.312591e-18   
8   ...   -3.794708e-18  1.129630e-01  1.703704e-01  1.851852e-03   
9   ...    1.192622e-18  9.657321e-02  9.345794e-03 -1.084202e-18   
10  ...   -1.832302e-17  2.095546e-15 -1.568190e-15 -7.968886e-18   
11  ...   -6.071532e-18 -6.938894e-16  1.000000e+00  3.957338e-18   
12  

In [21]:
kmeans.predict(dummydata)

array([10,  2, 13, ..., 17, 10,  7], dtype=int32)